#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18033
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace crispin.ExampleReportLibrary
{
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Text;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "1.5.4.0")]
    public partial class crispin_razor_example : RazorGenerator.Templating.RazorTemplateBase
    {
#line hidden

        public override void Execute()
        {


WriteLiteral("<?xml version=\"1.0\" encoding=\"UTF-8\" ?>\r\n<!DOCTYPE report [\r\n    <!ENTITY nbsp \"&" +
"#160;\">\r\n    <!ENTITY ldquo \"&#8220;\">\r\n    <!ENTITY lsquo \"&#8216;\">\r\n    <!ENT" +
"ITY rdquo \"&#8221;\">\r\n    <!ENTITY rsquo \"&#8217;\">\r\n    <!ENTITY quot \"&#34;\">\r" +
"\n]>\r\n");


            
            #line 10 "..\..\crispin.razor.example.cshtml"
  
    var packages = new[] {
        new { Origin =  "Cracow", Destination = "Dululu", Cost = 15.0m },
        new { Origin = "Emerald", Destination = "Dingo", Cost = 15.0m },
        new { Origin = "Duaringa", Destination = "Gladstone", Cost = 12.5m },
        new { Origin = "Dingo", Destination = "Dingo", Cost = 16.0m },
        new { Origin = "Dululu", Destination = "Duaringa", Cost = 12.5m },
        new { Origin = "Gladstone", Destination = "Dululu", Cost = 8.5m}
    };


            
            #line default
            #line hidden
WriteLiteral(@"<report>
    <title>Example report</title>
    <content>
        <pageSequence orientation=""portrait"">
            <htmlBlock>
                <p>To get this file converted into a .cs file by Razor, include the 
                'RazorGenerator.Templating' package and set the 'Custom Tool' property
                of this file to 'RazorGenerator'. Then to produce a PDF do this:</p>

<pre>
var report = new crispin_razor_example();<br />
var xrpt = report.TransformText();<br />
var converter = new PdfReportConverter();<br />
var pdfBits = converter.ConvertToBuffer(xrpt, ""Example report"");<br />
File.WriteAllBytes(""output.pdf"", pdfBits);
</pre>
            </htmlBlock>

            <contentBlock>
                <table>
                    <col width=""30%"" />
                    <col width=""30%"" />
                    <col width=""40%"" />
                    <thead>
                        <tr>
                            <th align=""left"">Origin</th>
                            <th align=""left"">Destination</th>
                            <th align=""right"">Weight (kg)</th>
                        </tr>
                    </thead>
                    <tbody>
");


            
            #line 51 "..\..\crispin.razor.example.cshtml"
                         foreach (var package in packages)
                        {

            
            #line default
            #line hidden
WriteLiteral("                            <tr>\r\n                                <td>");


            
            #line 54 "..\..\crispin.razor.example.cshtml"
                               Write(package.Origin);

            
            #line default
            #line hidden
WriteLiteral("</td>\r\n                                <td>");


            
            #line 55 "..\..\crispin.razor.example.cshtml"
                               Write(package.Destination);

            
            #line default
            #line hidden
WriteLiteral("</td>\r\n                                <td align=\"right\">");


            
            #line 56 "..\..\crispin.razor.example.cshtml"
                                             Write(package.Cost.ToString("C"));

            
            #line default
            #line hidden
WriteLiteral("</td>\r\n                            </tr>\r\n");


            
            #line 58 "..\..\crispin.razor.example.cshtml"
                        }

            
            #line default
            #line hidden
WriteLiteral(@"                    </tbody>
                </table>
            </contentBlock>

            <htmlBlock>
                <p><a href=""https://github.com/swxben/swxben.reporting/tree/master/src/swxben.reporting.ExampleReportLibrary"">More examples</a></p>
            </htmlBlock>
        </pageSequence>
    </content>
</report>

");


        }
    }
}
#pragma warning restore 1591
