#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18033
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace crispin.ExampleReportLibrary
{
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Text;
    
    #line 10 "..\..\CustomPageSetupTest.cshtml"
    using crispin.ExampleReportLibrary;
    
    #line default
    #line hidden
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "1.5.4.0")]
    public partial class CustomPageSetupTest : RazorGenerator.Templating.RazorTemplateBase
    {
#line hidden

        #line 11 "..\..\CustomPageSetupTest.cshtml"

    Header1 _header = new Header1 {
        Title = "Custom page setup test",
        Subtitle = "This header should go to the edge of the page"
    };

        #line default
        #line hidden

        public override void Execute()
        {


WriteLiteral("<?xml version=\"1.0\" encoding=\"UTF-8\" ?>\r\n<!DOCTYPE report [\r\n    <!ENTITY nbsp \"&" +
"#160;\">\r\n    <!ENTITY ldquo \"&#8220;\">\r\n    <!ENTITY lsquo \"&#8216;\">\r\n    <!ENT" +
"ITY rdquo \"&#8221;\">\r\n    <!ENTITY rsquo \"&#8217;\">\r\n    <!ENTITY quot \"&#34;\">\r" +
"\n]>\r\n");



WriteLiteral(@"

<report>
    <pageSetup>
        <pageMarginLeft>0</pageMarginLeft>
        <pageMarginRight>0</pageMarginRight>
        <pageMarginTop>0</pageMarginTop>
        <pageMarginBottom>0</pageMarginBottom>
        <pageLeaderMarginLeft>0</pageLeaderMarginLeft>
        <pageLeaderMarginRight>0</pageLeaderMarginRight>
        <pageLeaderMarginTop>0</pageLeaderMarginTop>
        <pageLeaderMarginBottom>0</pageLeaderMarginBottom>
    </pageSetup>
    <title>Custom page setup test</title>
    <content>
        <pageSequence orientation=""portrait"">
            ");


            
            #line 32 "..\..\CustomPageSetupTest.cshtml"
       Write(_header.TransformText());

            
            #line default
            #line hidden
WriteLiteral(@"
            <contentBlock>
                <table>
                    <col width=""10%"" />
                    <col width=""20%"" />
                    <col width=""60%"" />
                    <col width=""10%"" />
                    <thead>
                        <tr>
                            <th>&nbsp;</th>
                            <th align=""left"">Colour</th>
                            <th>&nbsp;</th>
                            <th>&nbsp;</th>
                        </tr>
                    </thead>
                    <tbody>
                        <tr><td>&nbsp;</td><td color=""#f00"">RED</td><td>&nbsp;</td><td>&nbsp;</td></tr>
                        <tr><td>&nbsp;</td><td color=""#0f0"">GREEN</td><td>&nbsp;</td><td>&nbsp;</td></tr>
                        <tr><td>&nbsp;</td><td color=""#00f"">BLUE</td><td>&nbsp;</td><td>&nbsp;</td></tr>
                    </tbody>
                </table>
            </contentBlock>
        </pageSequence>
    </content>
</report>");


        }
    }
}
#pragma warning restore 1591
