#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18033
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace crispin.ExampleReportLibrary
{
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Text;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "1.5.4.0")]
    public partial class Header1 : RazorGenerator.Templating.RazorTemplateBase
    {
#line hidden

        #line 2 "..\..\Header1.cshtml"

    public string Title{get;set;}
    public string Subtitle{get;set;}

        #line default
        #line hidden

        public override void Execute()
        {


WriteLiteral("\r\n");


WriteLiteral(@"

<htmlBlock>
    <table>
        <col width=""28%"" />
        <col width=""2%"" />
        <col width=""14%"" />
        <col width=""2%"" />
        <col width=""46%"" />
        <col width=""2%"" />
        <col width=""6%"" />
        <tbody>
            <tr>
              <td background-color=""#F2385A"">&nbsp;</td>
              <td>&nbsp;</td>
              <td background-color=""#F5A503"">&nbsp;</td>
              <td>&nbsp;</td>
              <td background-color=""#E9F1DF"" align=""right"" padding=""0.4cm"">
                <h2 space-before=""0cm"" space-after=""0cm"">");


            
            #line 23 "..\..\Header1.cshtml"
                                                    Write(Title);

            
            #line default
            #line hidden
WriteLiteral("</h2>\r\n                <h4 space-before=\"0cm\" space-after=\"0cm\">");


            
            #line 24 "..\..\Header1.cshtml"
                                                    Write(Subtitle);

            
            #line default
            #line hidden
WriteLiteral(@"</h4>
                <p>&nbsp;</p>
              </td>
              <td>&nbsp;</td>
              <td background-color=""#4AD9D9"">&nbsp;</td>
            </tr>
            <tr padding=""1.5cm""><td colspan=""7"">&nbsp;</td></tr>
        </tbody>
    </table>
    <br />
</htmlBlock>
");


        }
    }
}
#pragma warning restore 1591
