#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18033
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace crispin.ExampleReportLibrary
{
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Text;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "1.5.4.0")]
    public partial class LeftPaddedTable : RazorGenerator.Templating.RazorTemplateBase
    {
#line hidden

        public override void Execute()
        {


WriteLiteral(@"<?xml version=""1.0"" encoding=""UTF-8"" ?>
<!DOCTYPE report [
    <!ENTITY nbsp ""&#160;"">
    <!ENTITY ldquo ""&#8220;"">
    <!ENTITY lsquo ""&#8216;"">
    <!ENTITY rdquo ""&#8221;"">
    <!ENTITY rsquo ""&#8217;"">
    <!ENTITY quot ""&#34;"">
]>
<report>
    <title>Left padded table</title>
    <content>
        <pageSequence orientation=""portrait"">
        	<htmlBlock>
        		<h1>Left padded table</h1>
        		<p><small>See <a href=""https://github.com/swxben/swxben.reporting/issues/3"">https://github.com/swxben/swxben.reporting/issues/3</a></small><br /><br /><br /><br /></p>
        	</htmlBlock>
            <contentBlock padding-left=""1.1cm"">
                <table>
                    <col width=""50%"" />
                    <col width=""50%"" />
                    <thead>
                        <tr>
                            <th align=""left"">Name</th>
                            <th align=""right"">ID</th>
                        </tr>
                    </thead>
                    <tbody>
                        <tr><td>Ben</td>        <td align=""right"">123</td></tr>
                        <tr><td>Justine</td>    <td align=""right"">456</td></tr>
                        <tr><td>Ann</td>        <td align=""right"">445</td></tr>
                    </tbody>
                </table>
            </contentBlock>
        </pageSequence>
    </content>
</report>");


        }
    }
}
#pragma warning restore 1591
