#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18033
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace crispin.ExampleReportLibrary
{
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Text;
    
    #line 10 "..\..\Report1.cshtml"
    using crispin.ExampleReportLibrary;
    
    #line default
    #line hidden
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "1.5.4.0")]
    public partial class Report1 : RazorGenerator.Templating.RazorTemplateBase
    {
#line hidden

        #line 12 "..\..\Report1.cshtml"

    public IEnumerable<Package> Packages { get; set; }

        #line default
        #line hidden

        public override void Execute()
        {


WriteLiteral("<?xml version=\"1.0\" encoding=\"UTF-8\" ?>\r\n<!DOCTYPE report [\r\n    <!ENTITY nbsp \"&" +
"#160;\">\r\n    <!ENTITY ldquo \"&#8220;\">\r\n    <!ENTITY lsquo \"&#8216;\">\r\n    <!ENT" +
"ITY rdquo \"&#8221;\">\r\n    <!ENTITY rsquo \"&#8217;\">\r\n    <!ENTITY quot \"&#34;\">\r" +
"\n]>\r\n");


WriteLiteral("\r\n");


WriteLiteral("\r\n");


            
            #line 15 "..\..\Report1.cshtml"
  
    var header = new Header1
    {
        Title = "Report 1",
        Subtitle = "Subtitle"
    };
    var footer = new Footer1();


            
            #line default
            #line hidden
WriteLiteral("<report>\r\n    <title>Report 1</title>\r\n    <content>\r\n        <pageSequence orien" +
"tation=\"portrait\">\r\n            ");


            
            #line 27 "..\..\Report1.cshtml"
       Write(header.TransformText());

            
            #line default
            #line hidden
WriteLiteral(@"

            <contentBlock>
                <table type=""DataGridPas2"">
                    <col width=""30%"" />
                    <col width=""30%"" />
                    <col width=""40%"" />
                    <thead>
                        <tr>
                            <th align=""left"">Origin</th>
                            <th align=""left"">Destination</th>
                            <th align=""right"">Weight (kg)</th>
                        </tr>
                    </thead>
                    <tbody>
");


            
            #line 42 "..\..\Report1.cshtml"
                         foreach (var package in Packages)
                        {

            
            #line default
            #line hidden
WriteLiteral("                            <tr>\r\n                                <td>");


            
            #line 45 "..\..\Report1.cshtml"
                               Write(package.Origin);

            
            #line default
            #line hidden
WriteLiteral("</td>\r\n                                <td>");


            
            #line 46 "..\..\Report1.cshtml"
                               Write(package.Destination);

            
            #line default
            #line hidden
WriteLiteral("</td>\r\n                                <td align=\"right\">");


            
            #line 47 "..\..\Report1.cshtml"
                                             Write(package.Cost.ToString("C"));

            
            #line default
            #line hidden
WriteLiteral("</td>\r\n                            </tr>\r\n");


            
            #line 49 "..\..\Report1.cshtml"
                        }

            
            #line default
            #line hidden
WriteLiteral("                    </tbody>\r\n                </table>\r\n            </contentBloc" +
"k>\r\n\r\n            ");


            
            #line 54 "..\..\Report1.cshtml"
       Write(footer.TransformText());

            
            #line default
            #line hidden
WriteLiteral("\r\n        </pageSequence>\r\n    </content>\r\n</report>\r\n\r\n");


        }
    }
}
#pragma warning restore 1591
