#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18033
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace crispin.ExampleReportLibrary
{
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Text;
    
    #line 10 "..\..\RightAlignedNestedTable.cshtml"
    using crispin.ExampleReportLibrary;
    
    #line default
    #line hidden
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "1.5.4.0")]
    public partial class RightAlignedNestedTable : RazorGenerator.Templating.RazorTemplateBase
    {
#line hidden

        public override void Execute()
        {


WriteLiteral("<?xml version=\"1.0\" encoding=\"UTF-8\" ?>\r\n<!DOCTYPE report [\r\n    <!ENTITY nbsp \"&" +
"#160;\">\r\n    <!ENTITY ldquo \"&#8220;\">\r\n    <!ENTITY lsquo \"&#8216;\">\r\n    <!ENT" +
"ITY rdquo \"&#8221;\">\r\n    <!ENTITY rsquo \"&#8217;\">\r\n    <!ENTITY quot \"&#34;\">\r" +
"\n]>\r\n");



            
            #line 11 "..\..\RightAlignedNestedTable.cshtml"
  
    var header = new Header1 { Title = "Right Aligned Nested Table", Subtitle = "Illustrating https://github.com/swxben/swxben.reporting/issues/12" };
    var footer = new Footer1();


            
            #line default
            #line hidden
WriteLiteral("<report font-size=\"7pt\">\r\n\t<title>Right Aligned Nested Table</title>\r\n    <conten" +
"t>\r\n        <pageSequence orientation=\"portrait\">\r\n            ");


            
            #line 19 "..\..\RightAlignedNestedTable.cshtml"
       Write(header.TransformText());

            
            #line default
            #line hidden
WriteLiteral(@"
            
            <htmlBlock>
                <table>
                    <col width=""50%""/>
                    <col width=""50%""/>
                    <tbody>
                        <tr>
                            <td>LEFT</td>
                            <td align=""right"">
                                RIGHT<br/>
                                <table type=""DataGrid"">
                                    <col width=""10%""/>
                                    <col width=""10%""/>
                                    <tbody><tr><td>NESTED</td><td>TABLE</td></tr></tbody>
                                </table>
                            </td>
                        </tr>
                    </tbody>
                </table>
            </htmlBlock>

            ");


            
            #line 41 "..\..\RightAlignedNestedTable.cshtml"
       Write(footer.TransformText());

            
            #line default
            #line hidden
WriteLiteral("\r\n        </pageSequence>\r\n    </content>\r\n</report>");


        }
    }
}
#pragma warning restore 1591
