#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18033
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace crispin.ExampleReportLibrary
{
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Text;
    
    #line 11 "..\..\system_dot_web_tests.cshtml"
    using crispin.ExampleReportLibrary;
    
    #line default
    #line hidden
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "1.5.4.0")]
    public partial class system_dot_web_tests : System.Web.Razor.CustomRazorTemplateBase
    {
#line hidden
#line hidden
public System.Web.WebPages.HelperResult Embolden(string s) {
return new System.Web.WebPages.HelperResult(__razor_helper_writer => {



#line 16 "..\..\system_dot_web_tests.cshtml"
                            

#line default
#line hidden

WriteLiteralTo(@__razor_helper_writer, "    <strong>");



#line 17 "..\..\system_dot_web_tests.cshtml"
WriteTo(@__razor_helper_writer, s);

#line default
#line hidden

WriteLiteralTo(@__razor_helper_writer, "</strong>\r\n");



#line 18 "..\..\system_dot_web_tests.cshtml"

#line default
#line hidden

});

}


        public override void Execute()
        {


WriteLiteral("<?xml version=\"1.0\" encoding=\"UTF-8\" ?>\r\n");


WriteLiteral("<!DOCTYPE report [\r\n    <!ENTITY nbsp \"&#160;\">\r\n    <!ENTITY ldquo \"&#8220;\">\r\n " +
"   <!ENTITY lsquo \"&#8216;\">\r\n    <!ENTITY rdquo \"&#8221;\">\r\n    <!ENTITY rsquo " +
"\"&#8217;\">\r\n    <!ENTITY quot \"&#34;\">\r\n]>\r\n");



            
            #line 12 "..\..\system_dot_web_tests.cshtml"
  
    var header = new Header1 { Title = "I Can't Believe It's Not System.Web!", Subtitle = "" };
    var footer = new Footer1();


            
            #line default
            #line hidden


WriteLiteral("\r\n<report font-size=\"7pt\">\r\n\t<title>Static test 1</title>\r\n    <content>\r\n       " +
" <pageSequence orientation=\"portrait\">\r\n            ");


            
            #line 23 "..\..\system_dot_web_tests.cshtml"
       Write(Html.Raw(header.TransformText()));

            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n            <htmlBlock>\r\n                <p>Escape plain at values: ");


            
            #line 26 "..\..\system_dot_web_tests.cshtml"
                                       Write("<em>not emphasised</em>");

            
            #line default
            #line hidden
WriteLiteral("</p>\r\n                <p>Html.Raw(): ");


            
            #line 27 "..\..\system_dot_web_tests.cshtml"
                          Write(Html.Raw("<em>emphasised</em>"));

            
            #line default
            #line hidden
WriteLiteral("</p>\r\n                <p>Embolden helper: ");


            
            #line 28 "..\..\system_dot_web_tests.cshtml"
                               Write(Embolden("emboldened"));

            
            #line default
            #line hidden
WriteLiteral("</p>\r\n            </htmlBlock>\r\n\r\n            ");


            
            #line 31 "..\..\system_dot_web_tests.cshtml"
       Write(Html.Raw(footer.TransformText()));

            
            #line default
            #line hidden
WriteLiteral("\r\n        </pageSequence>\r\n    </content>\r\n</report>");


        }
    }
}
#pragma warning restore 1591
