#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18033
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace crispin.ExampleReportLibrary
{
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Text;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "1.5.4.0")]
    public partial class TableBackgroundTest : RazorGenerator.Templating.RazorTemplateBase
    {
#line hidden

        public override void Execute()
        {


WriteLiteral(@"<?xml version=""1.0"" encoding=""UTF-8"" ?>
<!DOCTYPE report [
    <!ENTITY nbsp ""&#160;"">
    <!ENTITY ldquo ""&#8220;"">
    <!ENTITY lsquo ""&#8216;"">
    <!ENTITY rdquo ""&#8221;"">
    <!ENTITY rsquo ""&#8217;"">
    <!ENTITY quot ""&#34;"">
]>
<report>
  <title>Table background test</title>
  <content>
    <pageSequence orientation=""portrait"">
        <htmlBlock>
            <table>
                <col width=""50%"" />
                <col width=""50%"" />
                <tbody>
                    <tr>
                      <td background-color=""#F2385A"">&nbsp;</td>
                      <td background-color=""#F5A503"">&nbsp;</td>
                    </tr>
                </tbody>
            </table>
            <br />
        </htmlBlock>
    </pageSequence>
  </content>
</report>

");


        }
    }
}
#pragma warning restore 1591
