#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18010
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace swxben.reporting.ExampleReportLibrary
{
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Text;
    
    #line 2 "..\..\Report1.cshtml"
    using swxben.reporting.ExampleReportLibrary;
    
    #line default
    #line hidden
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "1.5.0.0")]
    public partial class Report1 : RazorGenerator.Templating.RazorTemplateBase
    {
#line hidden

        #line 4 "..\..\Report1.cshtml"

    public IEnumerable<Package> Packages { get; set; }

        #line default
        #line hidden

        public override void Execute()
        {


WriteLiteral("\r\n");


WriteLiteral("\r\n");


WriteLiteral("\r\n\r\n<table>\r\n    <thead>\r\n        <tr>\r\n            <th>Origin</th>\r\n            " +
"<th>Destination</th>\r\n            <th>Weight (kg)</th>\r\n        </tr>\r\n    </the" +
"ad>\r\n    <tbody>\r\n");


            
            #line 17 "..\..\Report1.cshtml"
         foreach (var package in Packages)
        {

            
            #line default
            #line hidden
WriteLiteral("            <tr>\r\n                <td>");


            
            #line 20 "..\..\Report1.cshtml"
               Write(package.Origin);

            
            #line default
            #line hidden
WriteLiteral("</td>\r\n                <td>");


            
            #line 21 "..\..\Report1.cshtml"
               Write(package.Destination);

            
            #line default
            #line hidden
WriteLiteral("</td>\r\n                <td>");


            
            #line 22 "..\..\Report1.cshtml"
               Write(package.Cost.ToString("C"));

            
            #line default
            #line hidden
WriteLiteral("</td>\r\n            </tr>\r\n");


            
            #line 24 "..\..\Report1.cshtml"
        }

            
            #line default
            #line hidden
WriteLiteral("    </tbody>\r\n</table>\r\n\r\n");


        }
    }
}
#pragma warning restore 1591
