#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18010
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace swxben.reporting.ExampleReportLibrary
{
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Text;
    
    #line 4 "..\..\Report1.cshtml"
    using swxben.reporting.ExampleReportLibrary;
    
    #line default
    #line hidden
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "1.5.0.0")]
    public partial class Report1 : RazorGenerator.Templating.RazorTemplateBase
    {
#line hidden

        #line 6 "..\..\Report1.cshtml"

    public IEnumerable<Package> Packages { get; set; }

        #line default
        #line hidden

        public override void Execute()
        {


WriteLiteral("<?xml version=\"1.0\" encoding=\"UTF-8\" ?>\r\n<!DOCTYPE report [\r\n]>\r\n");


WriteLiteral("\r\n");


WriteLiteral("\r\n\r\n<report>\r\n    <title>Report 1</title>\r\n    <content>\r\n        <pageSequence o" +
"rientation=\"portrait\">\r\n            <htmlBlock>\r\n                <h1>Report 1</h" +
"1>\r\n                <h4>Generated ");


            
            #line 16 "..\..\Report1.cshtml"
                         Write(DateTime.Now.ToString());

            
            #line default
            #line hidden
WriteLiteral(@"</h4>
            </htmlBlock>

            <contentBlock>
                <table type=""DataGrid"">
                    <col width=""30%"" />
                    <col width=""70%"" />
                    <thead>
                        <tr>
                            <th>Origin</th>
                            <th>Destination</th>
                            <th>Weight (kg)</th>
                        </tr>
                    </thead>
                    <tbody>
");


            
            #line 31 "..\..\Report1.cshtml"
                         foreach (var package in Packages)
                        {

            
            #line default
            #line hidden
WriteLiteral("                            <tr>\r\n                                <td>");


            
            #line 34 "..\..\Report1.cshtml"
                               Write(package.Origin);

            
            #line default
            #line hidden
WriteLiteral("</td>\r\n                                <td>");


            
            #line 35 "..\..\Report1.cshtml"
                               Write(package.Destination);

            
            #line default
            #line hidden
WriteLiteral("</td>\r\n                                <td>");


            
            #line 36 "..\..\Report1.cshtml"
                               Write(package.Cost.ToString("C"));

            
            #line default
            #line hidden
WriteLiteral("</td>\r\n                            </tr>\r\n");


            
            #line 38 "..\..\Report1.cshtml"
                        }

            
            #line default
            #line hidden
WriteLiteral("                    </tbody>\r\n                </table>\r\n            </contentBloc" +
"k>\r\n        </pageSequence>\r\n    </content>\r\n</report>\r\n\r\n");


        }
    }
}
#pragma warning restore 1591
