#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18010
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace swxben.reporting.ExampleReportLibrary
{
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Text;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "1.5.0.0")]
    public partial class StaticTest1 : RazorGenerator.Templating.RazorTemplateBase
    {
#line hidden

        public override void Execute()
        {


WriteLiteral(@"<?xml version=""1.0"" encoding=""UTF-8"" ?>
<!DOCTYPE report [
]>
<report font-size=""7pt"">
	<title>Static test 1</title>
    <content>
        <pageSequence orientation=""portrait"">
            <htmlBlock>
                <h1>Static test 1</h1>
                <h4>Generated ");


            
            #line 10 "..\..\StaticTest1.cshtml"
                         Write(DateTime.Now.ToString());

            
            #line default
            #line hidden
WriteLiteral(@"</h4>
            </htmlBlock>

            <contentBlock>
                <table type=""DataGrid"">
                    <col width=""30%"" />
                    <col width=""70%"" />
                    <thead>
                        <tr>
                            <th align=""left"">ID</th>
                            <th align=""left"">Name</th>
                        </tr>
                    </thead>
                    <tbody>
                        <tr><td>123</td><td>Ben</td></tr>
                        <tr><td>456</td><td>Justine</td></tr>
                        <tr><td>445</td><td>Ann</td></tr>
                    </tbody>
                </table>
            </contentBlock>
        </pageSequence>
    </content>
</report>");


        }
    }
}
#pragma warning restore 1591
